version: '2'

services:

  elasticsearch:

    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0

    environment:

      - discovery.type=single-node

    ports:

      - 127.0.0.1:9200:9200

  kibana:

    image: docker.elastic.co/kibana/kibana:6.4.0

    ports:

      - 127.0.0.1:5601:5601